---
# SPINE1 specific data model

# Interfaces
interfaces:
  - name: Ethernet1
    description: "Link to Leaf1"
    type: trunk
    # allowed_vlans: [10, 20]
  - name: Ethernet2
    description: "Link to Leaf2"
    type: trunk
    # allowed_vlans: [10, 20] 
  - name: Ethernet3
    description: "Link to Leaf3"
    type: trunk
    # allowed_vlans: [20]
  - name: Ethernet4
    description: "Link to Leaf4"
    type: trunk
  - name: Ethernet48
    description: "Link to Spine2"
    type: trunk

# VLANs
vlans:
  - id: 10
    name: "ten"
  - id: 20
    name: "twenty"

svis:
  - id: 10
    desc: "ten"
    host_ip: "10.10.10.2/24"
    vip: "10.10.10.1"
  - id: 20
    desc: "twenty"
    host_ip: "20.20.20.2/24"
    vip: "20.20.20.1"

